services:
  frontend:
    image: ${FRONTEND_IMAGE}
    build:
      context: ./frontend
    container_name: ${FRONTEND_CONTAINER}
    restart: always
    ports:
      - "${FRONTEND_PORT}:80"
    environment:
      - API_BACKEND=backend:${BACKEND_PORT}
      - VITE_API_BACKEND=${VITE_API_BACKEND:-'/api'}
      - VITE_USE_MOCK=${VITE_USE_MOCK:-false}

  backend:
    image: ${BACKEND_IMAGE}
    build:
      context: ./backend
    container_name: ${BACKEND_CONTAINER}
    restart: always
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      - BACKEND_PORT=${BACKEND_PORT}
